### ISSUE TITLE
Prop types are failing

### ISSUE THREAD

**Issue by idmontie** [nerp-tech/react-fab#3]
From Antonio via email:

I installed the library using "yarn add react-fab", I only got one warning which I though I could ignore which was as follows: warning " > react-fab@1.0.0" has incorrect peer dependency "react@^15.4.1".

I then included the code in my project using your guide here: https://www.npmjs.com/package/react-fab. 

However, I got the following error when compiling the project: 

```
TypeError: Cannot read property 'bool' of undefined
./node_modules/react-fab/dist/components/FabButton.js

When I looked at your "FabButton.js", I realised it was expecting some props in the request; so I updated my code to reflect the below:
<Fab style={{ right: '20px', bottom: '20px' }}>
  <FabButton
  	className='FabButton'
  	active = {true}
    onClick = {this.toggleMuted}
    children = {"button-mute"}
    >
    +
  </FabButton>
  <FabActions>
    <FabAction
      className="button button-mute"
      onClick={this.toggleMuted}
      tooltip="Create Group"
    >
      G
    </FabAction>

  </FabActions>
</Fab>
```

However, I am still getting the same issue.  Can you please let me know what I am doing wrong on my end?

Please let me know if you need any further information in order to assist.

**Comment by idmontie** [comment]
Looks like PropTypes isn't in the version of React you are using. I am refactoring the code to use the `prop-types` package.

I'll release a new version `1.1.0` soon that will allow you to use the package with new versions of React.

**Comment by idmontie** [comment]
I have published version `1.1.0`. Please run `yarn upgrade react-fab` and let me know if it works for you.

**Comment by MRMTC** [comment]
Hi @idmontie,

Thanks so much for the quick response and assistance on this one :)  I tested and all is working well now. 

The only thing I noticed is that the "formatting/CSS" of the element is "off".  I get the buttons being imported into my project looking like the view below:
![image](https://user-images.githubusercontent.com/26508189/37625339-3008fb8c-2bd4-11e8-8ac6-f0228bc56e52.png)

Do you have any idea why this is happening?  Is there some sort of CSS file that I need to incorporate into my project for this?

Thanks again.

**Comment by idmontie** [comment]
Make sure you are importing the SASS stylesheet. See:

- [Usage docs](https://github.com/nerp-tech/react-fab#usage)
- [Or this working example](https://github.com/nerp-tech/react-fab-example), specifically, the [index.js](https://github.com/nerp-tech/react-fab-example/blob/master/src/index.js)

**Comment by MRMTC** [comment]
Thanks again @idmontie.  I managed to import the styling from the SASS stylesheet in "index.css; and all is working well :)

Thanks again for all the assistance!
