### ISSUE TITLE
Close on select

### ISSUE THREAD

**Issue by aogaili** [nerp-tech/react-fab#4]
Is there way to close the action buttons on select?

thanks for the component.

**Comment by idmontie** [comment]
It looks like I am not passing through the `onClick` handler that closes the FAB if you override it by passing in your own `onClick` event handler.

I'll mark this as a bug and get to it when I can.

**Comment by aogaili** [comment]
Thanks @idmontie ,  but how do you close it with the onClick handler? What is the desired API to toggle the actions menu?

**Comment by idmontie** [comment]
I think the default behavior should be to close the FAB when any`<FabAction>` is clicked. I can also provide an interface that will provide a `close` function from the `<Fab>` that can be called when using a ref.

**Comment by aogaili** [comment]
@idmontie  any progress on this?

**Comment by idmontie** [comment]
Completed in https://github.com/nerp-tech/react-fab/commit/649bbd68f67a1c490835e505484f1e1953c8241e.

I'll version bump and release it soon.

**Comment by idmontie** [comment]
Released in 1.2.0

**Comment by aogaili** [comment]
Thanks for implementing this 👍

**Comment by MRMTC** [comment]
Hi Guys :)

Firstly thanks for the great library :)  I was wondering if it was possible to have the FAB button "open" by default?  So currently when I click on the FAB button, the respective options are displayed.

Is there a way to have it open by default when the page loads?

Thanks.

**Comment by idmontie** [comment]
@MRMTC please feel free to open an issue so that we can track this new feature 👍

**Comment by MRMTC** [comment]
Sure, will do - thanks @idmontie :)
